# Generated by Django 5.1.3 on 2024-11-13 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_code', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=50)),
                ('experience_years', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('card_number', models.IntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=10)),
                ('birth_year', models.IntegerField()),
                ('category', models.CharField(choices=[('child', 'Child'), ('adult', 'Adult')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalStay',
            fields=[
                ('stay_code', models.AutoField(primary_key=True, serialize=False)),
                ('admission_date', models.DateField()),
                ('days_in_hospital', models.IntegerField()),
                ('daily_cost', models.FloatField()),
                ('discount_percent', models.FloatField()),
                ('doctor_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctor')),
                ('patient_card_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
    ]
